sudo: false

language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
      env:
        - COVERAGE=1
    - php: 7.3

install:
  - if [ $COVERAGE = "1" ]; then composer require --dev satooshi/php-coveralls; fi

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpstan analyze src -l max
  - vendor/bin/composer-require-checker check
  - if [ $COVERAGE = "1" ]; then mkdir -p build/logs && vendor/bin/kahlan --clover=build/logs/clover.xml; fi

after_success:
  - if [ $COVERAGE = "1" ]; then travis_retry php vendor/bin/php-coveralls -v; fi

notifications:
  email:
    - pasafama@gmail.com
